
###
POST http://localhost:3001/servizi/cancella
content-type: application/json


###
POST http://localhost:3001/servizi/getnomi
content-type: application/json


###
POST http://localhost:3001/servizi/add
content-type: application/json

{
    "nome":"prova",
    "cognome":"altro nome",
    "eta":33,
    "indirizzo": "via garibaldi",
    "localita":"roma"
}


